# Generated by Django 4.2.7 on 2025-11-01 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('source_links', models.JSONField(blank=True, default=list, verbose_name='Ссылки на исходные данные')),
                ('result_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на результат')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата начала')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assigner', 'Постановщик'), ('co_executor', 'Соисполнитель'), ('observer', 'Наблюдатель')], max_length=20, verbose_name='Роль')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль в задаче',
                'verbose_name_plural': 'Роли в задачах',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('blocked', 'Заблокирована')], default='todo', max_length=20, verbose_name='Статус')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Плановая трудоемкость (часы)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_items', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_task_created_5da2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['planned_end_date'], name='tasks_task_planned_d67e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrole',
            index=models.Index(fields=['task', 'user'], name='tasks_taskr_task_id_eb8ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrole',
            index=models.Index(fields=['user'], name='tasks_taskr_user_id_ab44d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskrole',
            unique_together={('task', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['task', 'status'], name='tasks_taski_task_id_5cd372_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['executor'], name='tasks_taski_executo_0ea226_idx'),
        ),
    ]
