# Generated by Django 4.2.7 on 2025-11-02 06:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата работы')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Часы')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='tasks.task', verbose_name='Задача')),
                ('task_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='tasks.taskitem', verbose_name='Подзадача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись времени',
                'verbose_name_plural': 'Записи времени',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['task', '-date'], name='timelogs_ti_task_id_2cd23c_idx'), models.Index(fields=['task_item', '-date'], name='timelogs_ti_task_it_fddf71_idx'), models.Index(fields=['user', '-date'], name='timelogs_ti_user_id_a01689_idx')],
            },
        ),
    ]
